### ISSUE TITLE
Dynamic help command

### ISSUE THREAD

**Issue by cytronicoder** [Developer-Dungeon-Studio/Crypto-Helper#17]
I have this script for my Discord bot that looks through the command directory and creates an embed based on the files. I think we can use the same script (with some modifications) with `/help` for Crypto Helper. I would love to be responsible for that.

Something like this:
```js
const commands = client.commands.map(command => {
            return {
                name: command.data.name,
                description: command.data.description
            }
        }).sort((a, b) => a.name.localeCompare(b.name));
// ...

const embed = new MessageEmbed()
            .addFields(commands.map(command => {
                return {
                    name: command.name,
                    value: command.description + `\nUsage: ${inlineCode("/" + command.name)}`,
                    inline: true
                }
            }))
// ...
```

**Comment by mezotv** [comment]
Hey if you want to put that into crypto helper you can just open a pull request or wait till i got time to put it in myself

**Comment by mezotv** [comment]
It would probably be better to split the commands in categorys to not have them mixed up

**Comment by mezotv** [comment]
you can look at the existing help command that includes the categorys
